[tools]
# mise use -g rust
rust = "beta"
"cargo:selene" = "latest"
"cargo:stylua" = "latest"
# "cargo:taplo-lsp" = "latest"
"cargo:emmylua_ls" = "latest"

# mise use -g node
node = "22.17.0"
nodejs = "22.17.0"
"npm:@biomejs/biome" = "latest"
"npm:prettier" = "latest"
"npm:yaml-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:fixjson" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:vim-language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:@postgrestools/postgrestools" = "latest"
"npm:deno" = "latest"

# mise use -g python
# pip install --user pipx
python = "3.13.4"
"pipx:psf/black" = "latest"

"terraform"  = "latest"
