"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$directory\
(${custom.jj}${custom.git_branch})\
${custom.git_status}\
$cmd_duration\
$line_break\
${custom.nix_shell}\
${custom.sudo}\
$jobs\
$status\
$character"""

command_timeout = 500

# move the rest of the prompt to the right
right_format = """$time"""

[time]
disabled = false
style = "yellow dimmed"
format = '[$time]($style) '
time_format = "%T"
# utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"

[username]
style_root = "red"
style_user = "purple"
format = "[$user]($style)@"

[hostname]
style = "yellow"
format = "[$hostname]($style) "

[cmd_duration]
format = "[\t $duration]($style) "

[character]
format = "$symbol "
success_symbol = "[›](bold green)"
error_symbol = "[›](bold red)"
vicmd_symbol = "[](bold fg:white,bg:#614b51)"

[jobs]
symbol = "󰄉(white dimmed)" # 
number_threshold = 1
symbol_threshold = 1
format = "$number$symbol"

# [custom.desk]
# description = "indicates whether you're in a desk-spawned shell"
# command = "(command desk -v &>/dev/null && (desk | grep -q 'No desk activated.' && echo '' || echo '🚀')) || echo ''"
# when = "true"


[custom.nix_shell]
symbol="󱄅"
command='''
  echo "$(echo $name | sed 's/-shell//')/$IN_NIX_SHELL"
'''
format = '\[[[$symbol](#ffffff) $output](#aaaaaa)\] '
when="[[ -n $IN_NIX_SHELL ]]"

# [nix_shell]
# impure_msg = '[-impure](#614b51)'
# pure_msg = '[-pure](#888888)'
# unknown_msg = '[-unknown](yellow)'
# format = '[[󱄅](#ffffff) $name$state](#aaaaaa) '

[custom.sudo]
description = "valid sudo timestamp marker"
command = "echo -n ''"
format = "[$symbol$output]($style) "
style = "bold fg:#614b51"
when = "sudo -vn &>/dev/null"

[custom.jj]
ignore_timeout = true
description = "The current jj status"
detect_folders = [ ".jj" ]
symbol = ""
# symbol = "󱗆 "
# hidden? 👻
command = '''
  jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
    separate(" ",
      change_id.shortest(4),
      bookmarks,
      "⋮",
      concat(
        if(conflict, "󰔷"),
        if(divergent, "󰧈"),
        if(hidden, "󰘓"),
        if(immutable, ""),
      ),
      raw_escape_sequence("\x1b[1;32m") ++ if(empty, "(empty)"),
      raw_escape_sequence("\x1b[1;32m") ++ coalesce(
        truncate_end(29, description.first_line(), "…"),
        "",
      ) ++ raw_escape_sequence("\x1b[0m"),
    )
  '
'''
        # "(no description set)",

[git_branch]
disabled = true
truncation_symbol = "…"
truncation_length = 20
symbol = "[](bold fg:#626262)" # 
format = "[$branch]($style)"
style = "italic fg:#7c8377" # 245

[custom.git_branch]
detect_folders = [".git", "!.jj"]
command = "starship module git_branch"
style = "italic fg:#7c8377" # 245
format = "[$output]($style)"

[git_status]
disabled = true
style = "#7c8377"
format = '([$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind](fg:$style) )'
ahead = "[ ](fg:white)" # ⇡
behind = "[ ](fg:white)" # ⇣
diverged = " 󰧈${ahead_count}${behind_count}"
modified = "[ 󰛄](fg:purple)" #•﯂
# modified = "[~${count}](fg:red)"
staged = "[ ](fg:green)"
# staged = "[$count](fg:green)"
conflicted = "[ 󰔷](bold fg:#FAB005)[${count}](fg:#d9bb80)"
stashed = "[ ${count}](fg:white)"
deleted = "[ ](fg:red)"
# deleted = "[$count](fg:red)"
renamed = "[ ](fg:white)"
# renamed = "[${count}](fg:white)"
untracked = "[ 󱏘](fg:#eeeeee)"
# untracked = "[󱏘${count}](fg:#7c8377)"

[custom.git_status]
detect_folders = [".git", "!.jj"]
command = "starship module git_status"
style = "#7c8377"
format = '[$output](fg:$style)'

[directory]
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = "bold blue"
