{ pkgs, ... }: {
  home.packages = with pkgs;
    [
      actionlint
      alejandra
      amber
      argc
      autoconf
      autogen
      automake
      basedpyright
      bash-language-server
      bat
      beam.packages.erlang_28.elixir_1_18
      beam.packages.erlang_28.erlang
      btop
      cachix
      charm-freeze
      chromedriver
      cmake
      delta
      deno
      direnv
      docker
      docker-compose
      eza
      fastfetch
      fd
      figlet
      fswatch
      fzf
      gawk
      gettext
      gh
      ghc
      git
      git-lfs
      gum
      harper
      hyperfine
      jq
      jujutsu
      just
      lazydocker
      lazygit
      lua-language-server
      lua5_1
      lua
      luarocks
      markdown-oxide
      marksman
      mise-flake.packages.${system}.mise
      neovim
      neovim-remote
      nil
      nix-direnv
      nixd
      nixfmt-rfc-style
      ninja
      nodePackages_latest.bash-language-server
      nodePackages_latest.typescript-language-server
      node
      nodejs
      openssl
      pkg-config
      pnpm
      prettierd
      python3
      ripgrep
      ruff
      # rust
      rust-analyzer
      sd
      selenium-server-standalone
      sesh
      shellcheck
      shfmt
      silicon
      smartcat
      sqlite-interactive
      stylua
      tailwindcss-language-server
      taplo
      tmux
      tokei
      tree-sitter
      twm
      typescript
      unstable.claude-code
      unstable.devenv
      unstable.opencode
      vim
      vscode-langservers-extracted
      vtsls
      weechat
      wget
      yaml-language-server
      yarn
      zig
      zk
      zls
      zsh
    ]
    ++ (
      if pkgs.stdenv.isLinux
      then [ gcc coreutils xclip unixtools.ifconfig inotify-tools ncurses5 ]
      else [ ]
    );
}
